name: base
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anaconda-anon-usage=0.5.0=py312hd6b623d_100
  - archspec=0.2.3=pyhd3eb1b0_0
  - boltons=23.0.0=py312hca03da5_0
  - brotli-python=1.0.9=py312h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.11.26=hca03da5_0
  - certifi=2024.8.30=py312hca03da5_0
  - cffi=1.17.1=py312h3eb5a62_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - conda=24.11.1=py312hca03da5_0
  - conda-anaconda-telemetry=0.1.1=py312hca03da5_0
  - conda-content-trust=0.2.0=py312hca03da5_1
  - conda-libmamba-solver=24.9.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py312hca03da5_0
  - conda-package-streaming=0.11.0=py312hca03da5_0
  - cryptography=43.0.3=py312h8026fc7_1
  - distro=1.9.0=py312hca03da5_0
  - expat=2.6.4=h313beb8_0
  - fmt=9.1.0=h48ca7d4_1
  - frozendict=2.4.2=py312hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py312hca03da5_0
  - jsonpatch=1.33=py312hca03da5_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=hf3e1bf2_1
  - libarchive=3.7.4=h8f13d7a_0
  - libcurl=8.9.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libiconv=1.16=h80987f9_3
  - libmamba=1.5.11=haeffa04_0
  - libmambapy=1.5.11=py312h15e39b3_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libsolv=0.7.24=h514c7bf_1
  - libssh2=1.11.1=h3e2b118_0
  - libxml2=2.13.5=h0b34f26_0
  - lz4-c=1.9.4=h313beb8_1
  - menuinst=2.2.0=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.15=h80987f9_0
  - packaging=24.1=py312hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pip=24.2=py312hca03da5_0
  - platformdirs=3.10.0=py312hca03da5_0
  - pluggy=1.5.0=py312hca03da5_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h80987f9_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.8=h99e199e_0
  - python.app=3=py312h80987f9_1
  - readline=8.2=h1a28f6b_0
  - reproc=14.2.4=h313beb8_2
  - reproc-cpp=14.2.4=h313beb8_2
  - requests=2.32.3=py312hca03da5_1
  - ruamel.yaml=0.18.6=py312h80987f9_0
  - ruamel.yaml.clib=0.2.8=py312h80987f9_0
  - setuptools=75.1.0=py312hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - tqdm=4.66.5=py312h989b03a_0
  - truststore=0.8.0=py312hca03da5_0
  - tzdata=2024b=h04d1e81_0
  - urllib3=2.2.3=py312hca03da5_0
  - wheel=0.44.0=py312hca03da5_0
  - xz=5.4.6=h80987f9_1
  - yaml-cpp=0.8.0=h313beb8_1
  - zlib=1.2.13=h18a0788_1
  - zstandard=0.23.0=py312h1a4646a_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - filelock==3.20.3
      - fsspec==2026.1.0
      - fswlib==0.9.9
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.4.1
      - sympy==1.14.0
      - torch==2.10.0
      - typing-extensions==4.15.0
prefix: /opt/homebrew/Caskroom/miniconda/base
